import{i,a as y,S as L}from"./assets/vendor-b52d9f5e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerpolicy&&(r.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?r.credentials="include":o.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC",s={form:document.querySelector("form"),list:document.querySelector(".gallery"),spanLoader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button"),input:document.querySelector(".form-input")};let d=1,u="",p=15;s.form.addEventListener("submit",F);async function F(e){if(e.preventDefault(),u=s.input.value.trim(),s.list.innerHTML="",s.loadButton.classList.add("hidden"),u==="")return i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Please,enter what do you want to find!"});d=1;try{const{hits:t,totalHits:a}=await g();m(t),B(a)}catch(t){i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${t}`})}f(),s.form.reset()}async function g(){s.spanLoader.classList.remove("hidden");const e=await y.get("https://pixabay.com/api/",{params:{key:"42112521-3ff4dfc201bab0977369cd2bc",q:`${u}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:p,page:d}}),{hits:t,totalHits:a}=e.data;return s.spanLoader.classList.add("hidden"),{hits:t,totalHits:a}}s.loadButton.addEventListener("click",async()=>{d++;try{const{hits:e,totalHits:t}=await g();m(e),w(),b(d,t)}catch(e){console.log(e),i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${e}`})}f()});function m(e){const t=e.map(({largeImageURL:a,webformatURL:c,tags:o,likes:r,views:n,comments:h,downloads:A})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${a}'>
    <img class='gallery-image' src='${c}' alt='${o}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${r}</p>
<p><span>Views</span> ${n}</p>
<p><span>Comments</span> ${h}</p>
<p><span>Downloads</span> ${A}</p>
</div>
 </li>`).join("");s.list.insertAdjacentHTML("beforeend",t)}function w(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function B(e){Math.ceil(e/p)>1&&s.loadButton.classList.remove("hidden"),e===0&&i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function b(e,t){const a=Math.ceil(t/p);e>a&&(s.loadButton.classList.add("hidden"),i.error({position:"topRight",messageColor:"#FFF",color:"#EF4040",iconUrl:l,message:"We're sorry, but you've reached the end of search results"}))}function f(){let e=new L(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});e.on("show.simpleLightbox"),e.refresh()}
//# sourceMappingURL=commonHelpers.js.map
