import{i as a,S as L,a as F}from"./assets/vendor-b52d9f5e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC",s={form:document.querySelector("form"),list:document.querySelector(".gallery"),spanLoader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button"),input:document.querySelector(".form-input")};let u=1,d="",p=15;s.form.addEventListener("submit",b);s.loadButton.addEventListener("click",w);async function m(){s.spanLoader.classList.remove("hidden");const e=await F.get("https://pixabay.com/api/",{params:{key:"42112521-3ff4dfc201bab0977369cd2bc",q:`${d}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:p,page:u}}),{hits:o,totalHits:n}=e.data;return s.spanLoader.classList.add("hidden"),{hits:o,totalHits:n}}async function b(e){if(e.preventDefault(),d=s.input.value.trim(),s.list.innerHTML="",s.loadButton.classList.add("hidden"),d==="")return a.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Please,enter what do you want to find!"});u=1;try{const{hits:o,totalHits:n}=await m();E(o),f(o),C(n)}catch(o){a.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${o}`})}h(),s.form.reset()}async function w(){u++;try{const{hits:e,totalHits:o}=await m();f(e),P(u,o)}catch(e){console.log(e),a.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${e}`})}B(),h()}function f(e){const o=e.map(({largeImageURL:n,webformatURL:c,tags:t,likes:r,views:i,comments:A,downloads:y})=>`<li class='gallery-item'>
             <a class='gallery-link' href='${n}'>
               <img class='gallery-image' src='${c}' alt='${t}'/>
             </a>
             <div class='container-app'>
              <p><span>Likes</span> ${r}</p>
              <p><span>Views</span> ${i}</p>
              <p><span>Comments</span> ${A}</p>
              <p><span>Downloads</span> ${y}</p>
             </div>
            </li>`).join("");s.list.insertAdjacentHTML("beforeend",o)}function B(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function E(e){e.length===0&&a.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function C(e){Math.ceil(e/p)>1&&s.loadButton.classList.remove("hidden")}function P(e,o){const n=Math.ceil(o/p);e>=n?(g.observe(s.list.lastChild),s.loadButton.classList.add("hidden")):g.unobserve(s.list.lastChild)}const g=new IntersectionObserver(S);function S(e,o){e.forEach(n=>{n.isIntersecting&&a.error({position:"topRight",messageColor:"#FFF",color:"#EF4040",iconUrl:l,message:"We're sorry, but you've reached the end of search results"})})}function h(){let e=new L(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});e.on("show.simpleLightbox"),e.refresh()}
//# sourceMappingURL=commonHelpers.js.map
