import{i as c,a as y,S as h}from"./assets/vendor-b52d9f5e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const p="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC",u=document.querySelector("form"),m=document.querySelector(".gallery"),d=document.querySelector(".loader"),i=document.querySelector(".load-button");u.addEventListener("submit",L);let l=1;async function L(r){r.preventDefault();const o=u.elements.search.value.trim();if(m.innerHTML="",i.style.display="none",o==="")return c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:p,position:"topRight",message:"Please,enter what do you want to find!"});d.style.display="block";try{const{hits:n,totalHits:s}=await A(o,l)}catch(n){c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:p,position:"topRight",message:`${n}`})}i.addEventListener("click",async()=>{l+=1,await A(o,l)}),w(),u.reset()}async function A(r,o){const n=await y.get("https://pixabay.com/api/",{params:{key:"42112521-3ff4dfc201bab0977369cd2bc",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o}}),{hits:s,totalHits:e}=n.data;return d.style.display="none",b(s),s.length===0&&(i.style.display="none",c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:p,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),{hits:s,totalHits:e}}function b(r){i.style.display="block";const o=r.map(({largeImageURL:n,webformatURL:s,tags:e,likes:t,views:a,comments:g,downloads:f})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${n}'>
    <img class='gallery-image' src='${s}' alt='${e}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${t}</p>
<p><span>Views</span> ${a}</p>
<p><span>Comments</span> ${g}</p>
<p><span>Downloads</span> ${f}</p>
</div>
 </li>`).join("");m.insertAdjacentHTML("beforeend",o)}function w(){let r=new h(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});r.on("show.simpleLightbox"),r.refresh()}
//# sourceMappingURL=commonHelpers.js.map
